### ISSUE TITLE
Unable to compose node

### ISSUE THREAD

**Issue by chendave** [intel/intelRSD#30]
I am able to compose/manage node based on Intel PODM, but after an unexpected outage in our lab, everything looks like in a mess, I cannot recover it anymore.

I am consisting see the below exceptions from the pod-manager-application.log, 
2017-10-27 01:12:38,513 [EE-ManagedScheduledExecutorService-EventsExecutor-Thread-1] ERROR c.i.p.d.e.event.EventSubscribeRunner - Error while subscribing to event service for '4c4c4544-434d-1001-8000-44a8421764ac': Couldn't create valid PodM Event Service destination

If am trying to allocate node, but I see the exceptions like this:
[allocate_node.txt](https://github.com/intel/intelRSD/files/1421106/allocate_node.txt)

And if I am trying to power off or restart some node, I see this exceptions:
[force_off.txt](https://github.com/intel/intelRSD/files/1421113/force_off.txt)

Looks like node is not is a right status, so I check the status and got the output like below:
[node_statue.txt](https://github.com/intel/intelRSD/files/1421123/node_statue.txt)

The node's status is indeed "Absent", so what does that mean by "Absent", how can I make it "Healthy" or "Enabled"? 

Could you anyone help me get it back to normal? thanks a lot!

**Comment by chendave** [comment]
BTW, is there any document has the details of those fields?

**Comment by tbykowsk** [comment]
Hi @chendave,

From your logs it looks like that the PODM cannot connect to the PSME Rest Server, which is responsible for communication with the PSME Compute Agent.
The PSME Compute Agent detects computer systems and reports them to the PSME Rest Server. If PODM cannot connect to this PSME Rest Server, then they stay in "Absent" state.
Please verify if the PSME Rest Server and the PSME Compute Agent started correctly, and if network connectivity between all aforementioned components was reestablished after the power outage.

You can find all the documentation on our page in [the Software tab](https://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-design/rack-scale-design-resources.html).

**Comment by chendave** [comment]
Hi @tbykowsk , thanks for your quick response, since I am quite new to the hardware/software requirement for the RSD solution, if you have something handy could you pls tell me how to check the status of PSEM agent and server? thanks!

**Comment by tbykowsk** [comment]
If you have the PSME Rest Server and the PSME Compute Agent installed as systemd services, then they should start automatically after the management host OS has booted. You can see their state by running `systemctl status psme-rest-server` and `systemctl status psme-compute`.  You may also check their logs using `journalctl -u psme-rest-server` and `journalctl -u psme-compute`.

Otherwise, if you run them as standalone binaries, you may start them manually on the management host OS  using command `/path_to_binary /path_to_its_configuration` (for example: `/usr/bin/psme-rest-server /etc/psme/psme-rest-server-configuration.json`) and you will see their logs printed on the console.

**Comment by chendave** [comment]
The issue has been solved, we just pull out the MC (Management Controller) and then push it in, since we found all nodes is powered off.  Thanks for the help!
