### ISSUE TITLE
Intel PODM 2.2 compose node POST Assemble fail by POSTMAN

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#89]
Dear Intel,
I have an issue that use POSTMAN to Compose Node in Intel PODM,
POST Allocate success , but POST Assemble fail,  DELETE success,
Could you help to check ? thank you

--------------------------------------------------------------
GET
https://10.99.240.83:8443/redfish/v1/Nodes/1
Find the Error -
ComposedNodeState	"Failed"

--------------------------------------------------------------
Intel PODM version : 2.2
Intel PSME Compute version :2.2 (PSME REST Server + PSME Compute Agent Simulator)
POSTMAN version : 6.0.7

--------------------------------------------------------------
Attachment -  2018-09-20-Intel-PODM-and-Intel-PSME-Compose-Node-by-POSTMAN.zip
[2018-09-20-Intel-PODM-and-Intel-PSME-Compose-Node-by-POSTMAN.zip](https://github.com/intel/intelRSD/files/2404469/2018-09-20-Intel-PODM-and-Intel-PSME-Compose-Node-by-POSTMAN.zip)

Attachment - fle -
2018-09-20-Intel-PODM-and-Intel-PSME-Compose-Node-by-POSTMAN.txt - the file has POSTMAN Commands

Attachment - Directory -
\ 1 - Intel PODM + Intel PSME - POST - Allocate\*.jpg - Test result for POST Allocate Node
\ 2 - Intel PODM + Intel PSME - POST - Assemble\*.jpg - Test result  for POST Assemble Node
\ 3 - Intel PODM + Intel PSME - DELETE\*.jpg - Test result  for DELETE Node

**Comment by RobertCMa** [comment]
Hi @housemic ,

The Compute Simulator sole purpose was to expose data about systems during the Deep Discovery phase. During the assembly PODM starts to send POST commands to a Compute Agent, which the Compute Simulator does not support. In short, the result is expected on PSME Compute Agent Simulator.

For the note, this deep discovery feature is no longer maintained since required data can be provide from  SMBIOS.

**Comment by housemic** [comment]
Dear RobertCMa,
The question can be closed, thank you.
House
